all: \
  _site/old/index.html \
  _site/old/app-empty.html \
  _site/old/app-navigation.html \
  _site/old/app-toolbar.html \
  _site/old/app-titlebar.html \
  _site/old/app-form.html \
  _site/old/app-form--banner.html \
  _site/old/app-form--wizard.html \
  _site/old/app-form--side-menu.html \
  _site/old/app-dialog.html \
  _site/old/datagrid.html \
  _site/old/registration.html \
  _site/old/web-empty.html \
  _site/old/blog-post.html \
  _site/old/tools-new-contract.html


_site/old/tools-new-contract.html: src/Smart/Html/Application.hs src/Smart/Html/Tools.hs
	mkdir -p $(dir $@)
	runghc -isrc/ bin/generate.hs --pretty tools-new-contract > $@

_site/old/%.html: src/Smart/Html/Application.hs src/Smart/Html/Website.hs
	mkdir -p $(dir $@)
	runghc -isrc/ bin/generate.hs --pretty $* > $@
